apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  labels:
    app: backend
    env: prod
    ver: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: prod
      ver: "1"
  template:
    metadata:
      labels:
        app: backend
        env: prod
        ver: "1"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP