apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
  labels:
    app: backend
    env: test
    ver: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      env: test
      ver: "2"
  template:
    metadata:
      labels:
        app: backend
        env: test
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP