apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod
  labels:
    app: frontend
    env: prod
    ver: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      env: prod
      ver: "2"
  template:
    metadata:
      labels:
        app: frontend
        env: prod
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP