apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-stating
  labels:
    app: frontend
    env: stating
    ver: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: stating
      ver: "2"
  template:
    metadata:
      labels:
        app: frontend
        env: stating
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP