apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-ha-host-zone
spec:
  selector:
    matchLabels:
      app: pod-ha-host-zone
  replicas: 3
  template:
    metadata:
      labels:
        app: pod-ha-host-zone
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: kuard
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pod-ha-host-zone
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pod-ha-host-zone
                topologyKey: topology.kubernetes.io/zone