apiVersion: apps/v1
kind: Deployment
metadata:
  name: antiaffinity-host
spec:
  selector:
    matchLabels:
      app: antiaffinity-host
  replicas: 3
  template:
    metadata:
      labels:
        app: antiaffinity-host
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: kuard
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - antiaffinity-host
              topologyKey: kubernetes.io/hostname