apiVersion: v1
kind: Pod
metadata:
  name: pod-antiaffinity-not-core
  labels:
    service: not-core
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: service
                operator: In
                values:
                  - core
          topologyKey: kubernetes.io/hostname
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "1024Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP