apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsschool-app
  annotations:
    kubernetes.io/change-cause: "Update image to kuard-amd64:2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsschool-app
  template:
    metadata:
      labels:
        app: opsschool-app
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP