apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

  
  Create cluster ip service for kandula monitoring port 5001 (kandula-service-monitor:5001):
  kubectl create -f svc-kandula-monitor.yaml    

  Add the kandula monitoring as job in promethus config map:
  kubectl edit cm prometheus-server -o yaml

  - job_name: kandula
      static_configs:
      - targets:
        - kandula-service-monitor:5001