apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-spread
  labels:
    app: kuard-spread
spec:
  selector:
    matchLabels:
      app: kuard-spread
  replicas: 4
  template:
    metadata:
      labels:
        app: kuard-spread
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: NotIn
                values:
                - us-east-1a
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: kuard-spread
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: kuard-spread
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: kuard
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP